### ISSUE TITLE
POST request magically transformed to GET request when POST endpoint is redirected

### ISSUE THREAD

**Issue by makc** [follow-redirects/follow-redirects#121]
looks like noone reposted [this issue](https://github.com/axios/axios/issues/2460) here, so I will :)

if server 301-redirects POST request, this module [changes request to GET](https://github.com/follow-redirects/follow-redirects/blob/master/index.js#L316) for no reason.

**Comment by RubenVerborgh** [comment]
> for no reason

Actually…

> > Automatic redirection needs to done with
   care for methods not known to be safe, as defined in Section 4.2.1,
   since the user might not wish to redirect an unsafe request.

—https://tools.ietf.org/html/rfc7231#section-6.4

> >  For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.

—https://tools.ietf.org/html/rfc7231#section-6.4.2

**Comment by makc** [comment]
@RubenVerborgh I see, so they changed the wording since rfc 2616:
!["erroneously change"](https://user-images.githubusercontent.com/242577/66691477-07683f00-ec97-11e9-86d6-e7037da8e6a8.png)

@vitalyster looks like this is the end :)

**Comment by vitalyster** [comment]
@RubenVerborgh what are these "historical reasons" in context of `follow-redirects` module? In what condition this behavior can be "desired"? Modern http client should NOT redirect "unsafe" methods

**Comment by RubenVerborgh** [comment]
> what are these "historical reasons" in context of `follow-redirects` module?

The fact that there exist servers that are not prepared for a `POST`, so we are erring on the safe side.

> In what condition this behavior can be "desired"?

When the server does not expect a `POST`.

> Modern http client should NOT redirect "unsafe" methods

That's not what the spec says:

> > Automatic redirection needs to done with
   care for methods not known to be safe, as defined in Section 4.2.1,
   since the user might not wish to redirect an unsafe request.

—https://tools.ietf.org/html/rfc7231#section-6.4

Servers can unambiguously use `307` to indicate the same method MUST be used:

> > The 307 (Temporary Redirect) status code indicates that the target
   resource resides temporarily under a different URI and the user agent
   MUST NOT change the request method if it performs an automatic
   redirection to that URI.  Since the redirection can change over time,
   the client ought to continue using the original effective request URI
   for future requests.

—https://tools.ietf.org/html/rfc7231#section-6.4.7

**Comment by vitalyster** [comment]
> Automatic redirection needs to done with care for methods not known to be safe,

What kind of "care" was applied from `follow-redirects` module side? Right now it just copy the "historical" behavior without any error/warning which make things hard to debug

**Comment by RubenVerborgh** [comment]
> What kind of "care" was applied from `follow-redirects` module side?

Follow the advice in 6.4.2, and be spec-compliant in general.

> Right now it just copy the "historical" behavior

I suppose we could make it a flag.

**Comment by torkelrogstad** [comment]
It would be very nice to make this a flag. I just spent several days debugging this issue in my app before arriving here.
