### ISSUE TITLE
debug version range can be wider

### ISSUE THREAD

**Issue by Shigma** [follow-redirects/follow-redirects#123]
Specifying `^3.0.0` may lead to unnecessarily duplicate `debug` packages since not every package needs to be compatible with node v4 which is no longer supported.

I think `>=3.0.0` or something like this may be much better.

**Comment by RubenVerborgh** [comment]
Specifying `>=` means a promise to be compatible with all future versions of `debug`, which is a promise we can’t make. Regarding support, please see #116 #177.

**Comment by wopian** [comment]
End of Life for Node 4 happened way back in 2018 (April 30). 

It would be a much nicer solution to release a new major version that just drops support for EOL node versions (4, 6 and 8) so legacy devices can continue using `follow-redirects@1` without issues and thus depend on `debug@4` again.

With the pin of `3.1.0` it is also missing out on 2 significant bug fixes from the final two `@3` releases.

Due to this, I have `debug@3.1.0` and `debug@4` in almost every NPM project I maintain and sometimes 3 when another transitive dependency depends on `debug@3`.

**Comment by RubenVerborgh** [comment]
That's a good point actually.

**Comment by jonathansamines** [comment]
@RubenVerborgh I'd be happy to create a pull request upgrading the debug versions while also dropping unsupported node versions from the project infrastructure. Would you accept a pull request?

**Comment by RubenVerborgh** [comment]
I turned `debug` into a peer dependency, so you are now able to use any version you want starting `follow-redirects@1.12.0` (currently building).
