### ISSUE TITLE
Support non-UTF8 location 

### ISSUE THREAD

**Issue by chinesedfan** [follow-redirects/follow-redirects#125]
When investigating https://github.com/axios/axios/issues/1804, I found that `follow-redirects` didn't handle non-UTF8 location. Code example,

```
const axios = require('axios')

;(async () => {
  const url = "http://www.smun.spb.ru"
  const head_response = await axios.head(url)

  console.log(head_response.headers)
})()
.then(() => { console.log("Success")})
.catch(() => { console.log("Error")})
```

The solution can be inspired by https://github.com/sindresorhus/got/pull/214, and the original discussion was in https://github.com/nodejs/node/issues/7928. With following patches, it can be fixed. If confirmed and without regression problems, I can provide a PR.

```
    // Perform the redirected request
-   var redirectUrl = url.resolve(this._currentUrl, location);
+   var redirectUrl = Buffer.from(location, 'binary').toString();
+   redirectUrl = (new url.URL(redirectUrl, this._currentUrl)).toString();
    debug("redirecting to", redirectUrl);
```

**Comment by RubenVerborgh** [comment]
Thanks, this is very helpful. Will fix with priority!

**Comment by RubenVerborgh** [comment]
Hmm, this is more problematic than I thought.

```
$ curl -i http://www.smun.spb.ru
HTTP/1.1 301 Moved Permanently
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html; charset=utf-8
Content-Language: ru
Location: http://смольный-институт.рф
Content-Length: 0
Date: Sat, 25 Jan 2020 22:21:54 GMT
Server: lighttpd/1.4.35
```

Note the contents of the `Location` header.

However, [RFC7231](https://tools.ietf.org/html/rfc7231#section-7.1.2) defines the contents of this header as `URI-reference`, which is defined in [RFC7230](https://tools.ietf.org/html/rfc7230#section-2.7) in terms of [RFC3986](https://tools.ietf.org/html/rfc3986#section-4.1). This specification states that

> URI producing applications must not use percent-encoding in host unless it is used
   to represent a UTF-8 character sequence.  When a non-ASCII registered
   name represents an internationalized domain name intended for
   resolution via the DNS, the name must be transformed to the IDNA
   encoding [RFC3490](https://tools.ietf.org/html/rfc3490) prior to name lookup.

Hence, I conclude that the server at `www.smun.spb.ru` is actually at fault.

Note in particular that curl also rejects it:

```
$ curl -i http://www.smun.spb.ru -L
HTTP/1.1 301 Moved Permanently
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html; charset=utf-8
Content-Language: ru
Location: http://смольный-институт.рф
Content-Length: 0
Date: Sat, 25 Jan 2020 22:30:38 GMT
Server: lighttpd/1.4.35

curl: (6) Could not resolve host: %d1%81%d0%bc%d0%be%d0%bb%d1%8c%d0%bd%d1%8b%d0%b9-%d0%b8%d0%bd%d1%81%d1%82%d0%b8%d1%82%d1%83%d1%82.%d1%80%d1%84
```

However, I also note that some browsers perform the redirect.

So the solution chosen by @luanmuniz and @sindresorhus in https://github.com/sindresorhus/got/pull/214 seems like one possibility, but not the only possibility. There might even be security considerations in decoding the `Location` header value.

Additionally issue is that there's no easy way to test: if I manually set `Location` to `http://смольный-институт.рф` in the HTTP response, then Node complains (confirming that this is incorrect to do).

I think that `follow-redirects` should actually return an error (rather than crash or resolve). Would you object to that resolution?

**Comment by chinesedfan** [comment]
> Hence, I conclude that the server at www.smun.spb.ru is actually at fault.

Right, when facing invalid inputs, a library can choose two options: throwing an error or handling it. I can accept both choices. Rejecting with an error may require users to solve the root case, but will keep the library clean and neat.

**Comment by dinnouti** [comment]
The ability to handle the error would be great. I am processing 10k urls and just crashes without giving me a chance to investigate and clean the faulty URL from my list of URLs.

**Comment by RubenVerborgh** [comment]
@dinnouti We have that now in the latest version thanks to 137c8cf467c52c0583502bb611aab7e65704a929.

**Comment by netroy** [comment]
I'm seeing this issue on a couple of URLs that seem to work fine elsewhere, so I've created #246 in an attempt to address this.
