### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by kieronbos** [follow-redirects/follow-redirects#136]
Hi, I get this when I use this
```
Error: getaddrinfo ENOTFOUND https://t.co/L4SlfsLvUi
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

Using this code, where `url` is the URL I am looking to detect & return the final url.
`return https.request({host: url}, response => {console.log(response.responseUrl)});`

**Comment by RubenVerborgh** [comment]
This does not work with Node built-in `https` either, so it correctly fails with the same error when using `follow-redirects`.

The bug is that you are passing `{host: url}`: you are saying that `https://t.co/L4SlfsLvUi` is a host, whereas it is a URL. If you pass `url` instead, it will be better (but don't forget to `.end()` the request). I suggest testing with the Node built-in `https` first if you are unsure how the API is used exactly.
