### ISSUE TITLE
'Debug' module not found error

### ISSUE THREAD

**Issue by hrithikwins** [follow-redirects/follow-redirects#222]
I'm using a nextjs 13 project and this is the error that's throwing in my console constantly 
```
./node_modules/follow-redirects/debug.js
Module not found: Can't resolve 'debug' in '/media/hrithik/56377dfe-6a03-489f-8930-9fc71d2e8366/@home/hrithikwins/workspace/my-projects/web3/006-graphity/wix-metaverse/node_modules/follow-redirects'
Did you mean './debug'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /media/hrithik/56377dfe-6a03-489f-8930-9fc71d2e8366/@home/hrithikwins/workspace/my-projects/web3/006-graphity/wix-metaverse).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

I went and commented out that line ( line 7 in index.js) and now it no longer throws the error (after I delete the .next folder and rerun)

**Comment by hrithikwins** [comment]
Build logs in vercel
![image](https://user-images.githubusercontent.com/42163313/201457159-548ad70a-32f5-4b72-842f-ced41067d479.png)

**Comment by RubenVerborgh** [comment]
If you're using Next.js, I assume you are building a client-side library. follow-redirects is a Node.js module that you don't need in the browser, because browsers include this functionality by default.

Basically, something else is wrong in your configuration that follow-redirects is being loaded in the first place. I.e., it doesn't make sense to explain how to get rid of debug, because you need to get rid of all of follow-redirects 🙂

Maybe the Axios people can help with compiling for the browser!

**Comment by Negan1911** [comment]
@RubenVerborgh It's possible to use axios on the server side, on my case I use it on the server only (since I want to call on a API) but I can't because of this "debug" module, even if I install it it's an ESM so it doesn't work.

**Comment by RubenVerborgh** [comment]
I wonder if anyone is actually using debug. You might be able to patch it out: https://www.npmjs.com/package/patch-package
